# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=20000']
  - repo: local
    hooks:
      {%- if cookiecutter.use_black == 'y' %}
      - id: black
        name: black
        entry: poetry run black src
        language: system
        types: [python]
      {%- endif %}
      {%- if cookiecutter.use_flake8 == 'y' %}
      - id: flake8
        name: flake8
        entry: poetry run flake8 --max-line-length=90
        language: system
        pass_filenames: true
        types: [python]
      {%- endif %}
      {%- if cookiecutter.use_mypy == 'y' %}
      - id: mypy
        name: mypy
        files: ^src/
        entry: poetry run mypy  --follow-imports=skip --ignore-missing-imports --disallow-untyped-defs -- src
        language: system
        pass_filenames: true
        types: [python]
        pass_filenames: false
      {%- endif %}
